# https://docs.github.com/en/code-security/reference/supply-chain-security/dependabot-options-reference
# https://docs.github.com/en/code-security/tutorials/secure-your-dependencies/optimizing-pr-creation-version-updates
version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  cooldown:
    semver-major-days: 7
    semver-minor-days: 3
    semver-patch-days: 2
    default-days: 7
- package-ecosystem: npm
  directory: "/"
  allow:
    - dependency-name: "lexical"
    - dependency-name: "@lexical/*"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  cooldown:
    semver-major-days: 7
    semver-minor-days: 3
    semver-patch-days: 2
    default-days: 7
  groups:
    lexical:
      patterns:
        - "lexical"
        - "@lexical/*"
- package-ecosystem: github-actions
  directory: "/"
  groups:
    github-actions:
      patterns:
        - "*"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  cooldown:
    default-days: 7
